name: note_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.1
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  getwidget: ^4.0.0
  file_picker: ^6.0.0
  firebase_storage: ^11.3.1
  firebase_analytics: ^10.6.2
  firebase_auth: ^4.12.0
  google_sign_in: ^6.1.5
  get:
  flutter_launcher_icons: ^0.13.1
  flutter_quill:
    git: https://github.com/singerdmx/flutter-quill.git
  image:
  path_provider: ^2.1.1
#  record: ^5.0.1
#  assets_audio_player:
#  audioplayers:
##  flutter_sound_lite: ^8.5.0
#  provider:
#  flutter_sound: ^9.1.9
#  permission_handler:
  image_editor_plus: ^1.0.3
  shared_preferences:
  social_media_recorder: ^1.1.1
#  audio_waveforms: ^1.0.4
#  audioplayers: ^5.2.0
  just_audio: ^0.9.35




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/notes.png
    - assets/background.jpg
    - assets/avatar.png
    - assets/user.png
    - assets/statics/facebook.png
    - assets/statics/github.png
    - assets/statics/google.png
    - assets/audio1.mp3


